server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://123.60.14.4:8761/eureka
  instance:
    prefer-ip-address: true


spring:
  application:
    name: OtherService
  datasource:
    url: jdbc:mysql://101.34.7.144:3306/ETCDB
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.edu.xmu.haruki.other.model
  configuration:
    map-underscore-to-camel-case: true
