server:
  port: 8082


spring:
  application:
    name: EnvironmentService
  datasource:
    url: jdbc:mysql://localhost:3306/ETCDB
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456


eureka:
  client:
    service-url:
      defaultZone: http://101.34.7.144:8761/eureka
  instance:
    prefer-ip-address: true


mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
