server:
  port: 8999
eureka:
  instance:
    hostname: gateway #eureka服务端的实例名称
    prefer-ip-address: true #访问路径可以显示IP地址
  client:
    register-with-eureka: true     #false表示不向注册中心注册自己。
    fetch-registry: true     #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      #集群指向其它eureka
      defaultZone: http://127.0.0.1:8761/eureka/
spring:
  application:
    name: SpringCloudGateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns:
              - "*"
            allowCredentials: true
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
      discovery:
        locator:
          enabled: true
      routes:
        - id: userService #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: lb://OTHERSERVICE         #匹配后提供服务的路由地址
          predicates:
            - Path=/user/** # 断言，路径相匹配的进行路由
          filters:
            - name: CircuitBreaker
              args:
                name: fallbackmssage
                fallbackUri: forward:/fallback/message
        - id: fallbackService
          uri: lb://SpringCloudGateway
          predicates:
            - Path=/fallback/message
        - id: manageService
          uri: lb://OtherService
          predicates:
            - Path=/control/**
          filters:
            - name: CircuitBreaker
              args:
                name: fetchIngredients
                fallbackUri: forward:/fallback/message
        - id: environmentService
          uri: lb://EnvironmentService
          predicates:
            - Path=/environment/**, /record/**, /sensor/**
          filters:
            - name: CircuitBreaker
              args:
                name: fetchIngredients
                fallbackUri: forward:/fallback/message
        - id: userLogin
          uri: lb://OTHERSERVICE
          predicates:
            - Path=/login
          filters:
            - name: CircuitBreaker
              args:
                name: fetchIngredients
                fallbackUri: forward:/fallback/message
        - id: dashboardService
          uri: lb://DASHBOARDSERVICE
          predicates:
            - Path=/dashboard/**
          filters:
            - name: CircuitBreaker
              args:
                name: fetchIngredients
                fallbackUri: forward:/fallback/message
